version: '3'

services:

  app:
    container_name: youtack
    #network_mode: "host"
    build: youtrack/.
    ports:
      - "8080:8080"
    networks:
      - default

  #app2:
  #    container_name: twig
  #    build:
  #      context: .
  #      dockerfile: Dockerfile-spring4shell
  #    depends_on:
  #      - db
  #    ports:
  #      - "8081:8081"
  #    networks:
  #      - default

volumes:
  db:
    driver: local

networks:
  default:
    name: default_network
