version: '3'

services:

  app:
    container_name: youtrack_vul
    #network_mode: "host"
    build:
        context: youtrack/.
        dockerfile: Dockerfile-vulnerable
    ports:
      - "8080:8080"
    networks:
      - default

  app2:
    container_name: youtrack_base
    build:
      context: youtrack/.
      dockerfile: Dockerfile-baseline
    ports:
      - "8081:8081"
    networks:
      - default

  app3:
    container_name: freemarker
    build: freemarker/.
    ports:
      - "8082:8080"
    networks:
      - default

  #app4:
  #    container_name: twig
  #    build:
  #      context: .
  #      dockerfile: twig/.
  #    depends_on:
  #      - db
  #    ports:
  #      - "8081:8081"
  #    networks:
  #      - default

volumes:
  db:
    driver: local

networks:
  default:
    name: default_network
