FROM tomcat:9.0
#FROM tomcat:8.0.36-jre8

#COPY /target/CS5331SSTI.war /usr/local/tomcat/webapps/
COPY /CS5331SSTI/target/CS5331SSTI.war /var/lib/tomcat9/webapps/
#COPY /tomcat/ /usr/local/tomcat/webapps/ROOT/

#ENTRYPOINT ["catalina.sh", "run"]
